services:
  tp3-mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./TP_3-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: bootcamp2020
      MYSQL_DATABASE: rhymedb
      MYSQL_USER: Rhyme
      MYSQL_PASSWORD: 89qFd4!mWy6Uyk^@MWWC
    ports:
      - "3306:3306"
    networks:
      - rhymenet
  
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rhymenet
    depends_on:
      - tp3-mysql

networks:
  rhymenet:
    driver: bridge