name: Test code on push
on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest # os
    steps: # followed steps
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
